// Code generated by mockery v2.53.6. DO NOT EDIT.

package service

import (
	context "context"

	domain "github.com/dengankarya/connector/internal/payment/domain"
	mock "github.com/stretchr/testify/mock"

	repository "github.com/dengankarya/connector/internal/payment/repository"

	uuid "github.com/google/uuid"
)

// MockTransactionStore is an autogenerated mock type for the TransactionStore type
type MockTransactionStore struct {
	mock.Mock
}

type MockTransactionStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionStore) EXPECT() *MockTransactionStore_Expecter {
	return &MockTransactionStore_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, txn
func (_m *MockTransactionStore) Create(ctx context.Context, txn *domain.PaymentTransaction) error {
	ret := _m.Called(ctx, txn)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.PaymentTransaction) error); ok {
		r0 = rf(ctx, txn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTransactionStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - txn *domain.PaymentTransaction
func (_e *MockTransactionStore_Expecter) Create(ctx interface{}, txn interface{}) *MockTransactionStore_Create_Call {
	return &MockTransactionStore_Create_Call{Call: _e.mock.On("Create", ctx, txn)}
}

func (_c *MockTransactionStore_Create_Call) Run(run func(ctx context.Context, txn *domain.PaymentTransaction)) *MockTransactionStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.PaymentTransaction))
	})
	return _c
}

func (_c *MockTransactionStore_Create_Call) Return(_a0 error) *MockTransactionStore_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionStore_Create_Call) RunAndReturn(run func(context.Context, *domain.PaymentTransaction) error) *MockTransactionStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockTransactionStore) GetByID(ctx context.Context, id uuid.UUID) (*domain.PaymentTransaction, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.PaymentTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.PaymentTransaction, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.PaymentTransaction); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PaymentTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionStore_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockTransactionStore_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockTransactionStore_Expecter) GetByID(ctx interface{}, id interface{}) *MockTransactionStore_GetByID_Call {
	return &MockTransactionStore_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockTransactionStore_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockTransactionStore_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTransactionStore_GetByID_Call) Return(_a0 *domain.PaymentTransaction, _a1 error) *MockTransactionStore_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionStore_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.PaymentTransaction, error)) *MockTransactionStore_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIDForUpdate provides a mock function with given fields: ctx, id
func (_m *MockTransactionStore) GetByIDForUpdate(ctx context.Context, id uuid.UUID) (*domain.PaymentTransaction, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDForUpdate")
	}

	var r0 *domain.PaymentTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.PaymentTransaction, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.PaymentTransaction); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PaymentTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionStore_GetByIDForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIDForUpdate'
type MockTransactionStore_GetByIDForUpdate_Call struct {
	*mock.Call
}

// GetByIDForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockTransactionStore_Expecter) GetByIDForUpdate(ctx interface{}, id interface{}) *MockTransactionStore_GetByIDForUpdate_Call {
	return &MockTransactionStore_GetByIDForUpdate_Call{Call: _e.mock.On("GetByIDForUpdate", ctx, id)}
}

func (_c *MockTransactionStore_GetByIDForUpdate_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockTransactionStore_GetByIDForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTransactionStore_GetByIDForUpdate_Call) Return(_a0 *domain.PaymentTransaction, _a1 error) *MockTransactionStore_GetByIDForUpdate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionStore_GetByIDForUpdate_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.PaymentTransaction, error)) *MockTransactionStore_GetByIDForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// GetByOrderNumber provides a mock function with given fields: ctx, tenantID, orderNumber
func (_m *MockTransactionStore) GetByOrderNumber(ctx context.Context, tenantID int64, orderNumber string) (*domain.PaymentTransaction, error) {
	ret := _m.Called(ctx, tenantID, orderNumber)

	if len(ret) == 0 {
		panic("no return value specified for GetByOrderNumber")
	}

	var r0 *domain.PaymentTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) (*domain.PaymentTransaction, error)); ok {
		return rf(ctx, tenantID, orderNumber)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) *domain.PaymentTransaction); ok {
		r0 = rf(ctx, tenantID, orderNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PaymentTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = rf(ctx, tenantID, orderNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionStore_GetByOrderNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByOrderNumber'
type MockTransactionStore_GetByOrderNumber_Call struct {
	*mock.Call
}

// GetByOrderNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID int64
//   - orderNumber string
func (_e *MockTransactionStore_Expecter) GetByOrderNumber(ctx interface{}, tenantID interface{}, orderNumber interface{}) *MockTransactionStore_GetByOrderNumber_Call {
	return &MockTransactionStore_GetByOrderNumber_Call{Call: _e.mock.On("GetByOrderNumber", ctx, tenantID, orderNumber)}
}

func (_c *MockTransactionStore_GetByOrderNumber_Call) Run(run func(ctx context.Context, tenantID int64, orderNumber string)) *MockTransactionStore_GetByOrderNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string))
	})
	return _c
}

func (_c *MockTransactionStore_GetByOrderNumber_Call) Return(_a0 *domain.PaymentTransaction, _a1 error) *MockTransactionStore_GetByOrderNumber_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionStore_GetByOrderNumber_Call) RunAndReturn(run func(context.Context, int64, string) (*domain.PaymentTransaction, error)) *MockTransactionStore_GetByOrderNumber_Call {
	_c.Call.Return(run)
	return _c
}

// GetByOrderNumberForUpdate provides a mock function with given fields: ctx, tenantID, orderNumber
func (_m *MockTransactionStore) GetByOrderNumberForUpdate(ctx context.Context, tenantID int64, orderNumber string) (*domain.PaymentTransaction, error) {
	ret := _m.Called(ctx, tenantID, orderNumber)

	if len(ret) == 0 {
		panic("no return value specified for GetByOrderNumberForUpdate")
	}

	var r0 *domain.PaymentTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) (*domain.PaymentTransaction, error)); ok {
		return rf(ctx, tenantID, orderNumber)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) *domain.PaymentTransaction); ok {
		r0 = rf(ctx, tenantID, orderNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PaymentTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = rf(ctx, tenantID, orderNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionStore_GetByOrderNumberForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByOrderNumberForUpdate'
type MockTransactionStore_GetByOrderNumberForUpdate_Call struct {
	*mock.Call
}

// GetByOrderNumberForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID int64
//   - orderNumber string
func (_e *MockTransactionStore_Expecter) GetByOrderNumberForUpdate(ctx interface{}, tenantID interface{}, orderNumber interface{}) *MockTransactionStore_GetByOrderNumberForUpdate_Call {
	return &MockTransactionStore_GetByOrderNumberForUpdate_Call{Call: _e.mock.On("GetByOrderNumberForUpdate", ctx, tenantID, orderNumber)}
}

func (_c *MockTransactionStore_GetByOrderNumberForUpdate_Call) Run(run func(ctx context.Context, tenantID int64, orderNumber string)) *MockTransactionStore_GetByOrderNumberForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string))
	})
	return _c
}

func (_c *MockTransactionStore_GetByOrderNumberForUpdate_Call) Return(_a0 *domain.PaymentTransaction, _a1 error) *MockTransactionStore_GetByOrderNumberForUpdate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionStore_GetByOrderNumberForUpdate_Call) RunAndReturn(run func(context.Context, int64, string) (*domain.PaymentTransaction, error)) *MockTransactionStore_GetByOrderNumberForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// GetByProviderInvoiceID provides a mock function with given fields: ctx, provider, invoiceID
func (_m *MockTransactionStore) GetByProviderInvoiceID(ctx context.Context, provider string, invoiceID string) (*domain.PaymentTransaction, error) {
	ret := _m.Called(ctx, provider, invoiceID)

	if len(ret) == 0 {
		panic("no return value specified for GetByProviderInvoiceID")
	}

	var r0 *domain.PaymentTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.PaymentTransaction, error)); ok {
		return rf(ctx, provider, invoiceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.PaymentTransaction); ok {
		r0 = rf(ctx, provider, invoiceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PaymentTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, provider, invoiceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionStore_GetByProviderInvoiceID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByProviderInvoiceID'
type MockTransactionStore_GetByProviderInvoiceID_Call struct {
	*mock.Call
}

// GetByProviderInvoiceID is a helper method to define mock.On call
//   - ctx context.Context
//   - provider string
//   - invoiceID string
func (_e *MockTransactionStore_Expecter) GetByProviderInvoiceID(ctx interface{}, provider interface{}, invoiceID interface{}) *MockTransactionStore_GetByProviderInvoiceID_Call {
	return &MockTransactionStore_GetByProviderInvoiceID_Call{Call: _e.mock.On("GetByProviderInvoiceID", ctx, provider, invoiceID)}
}

func (_c *MockTransactionStore_GetByProviderInvoiceID_Call) Run(run func(ctx context.Context, provider string, invoiceID string)) *MockTransactionStore_GetByProviderInvoiceID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTransactionStore_GetByProviderInvoiceID_Call) Return(_a0 *domain.PaymentTransaction, _a1 error) *MockTransactionStore_GetByProviderInvoiceID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionStore_GetByProviderInvoiceID_Call) RunAndReturn(run func(context.Context, string, string) (*domain.PaymentTransaction, error)) *MockTransactionStore_GetByProviderInvoiceID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByProviderInvoiceIDForUpdate provides a mock function with given fields: ctx, provider, invoiceID
func (_m *MockTransactionStore) GetByProviderInvoiceIDForUpdate(ctx context.Context, provider string, invoiceID string) (*domain.PaymentTransaction, error) {
	ret := _m.Called(ctx, provider, invoiceID)

	if len(ret) == 0 {
		panic("no return value specified for GetByProviderInvoiceIDForUpdate")
	}

	var r0 *domain.PaymentTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.PaymentTransaction, error)); ok {
		return rf(ctx, provider, invoiceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.PaymentTransaction); ok {
		r0 = rf(ctx, provider, invoiceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PaymentTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, provider, invoiceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionStore_GetByProviderInvoiceIDForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByProviderInvoiceIDForUpdate'
type MockTransactionStore_GetByProviderInvoiceIDForUpdate_Call struct {
	*mock.Call
}

// GetByProviderInvoiceIDForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - provider string
//   - invoiceID string
func (_e *MockTransactionStore_Expecter) GetByProviderInvoiceIDForUpdate(ctx interface{}, provider interface{}, invoiceID interface{}) *MockTransactionStore_GetByProviderInvoiceIDForUpdate_Call {
	return &MockTransactionStore_GetByProviderInvoiceIDForUpdate_Call{Call: _e.mock.On("GetByProviderInvoiceIDForUpdate", ctx, provider, invoiceID)}
}

func (_c *MockTransactionStore_GetByProviderInvoiceIDForUpdate_Call) Run(run func(ctx context.Context, provider string, invoiceID string)) *MockTransactionStore_GetByProviderInvoiceIDForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTransactionStore_GetByProviderInvoiceIDForUpdate_Call) Return(_a0 *domain.PaymentTransaction, _a1 error) *MockTransactionStore_GetByProviderInvoiceIDForUpdate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionStore_GetByProviderInvoiceIDForUpdate_Call) RunAndReturn(run func(context.Context, string, string) (*domain.PaymentTransaction, error)) *MockTransactionStore_GetByProviderInvoiceIDForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// ListByTenant provides a mock function with given fields: ctx, tenantID, p
func (_m *MockTransactionStore) ListByTenant(ctx context.Context, tenantID int64, p repository.ListParams) ([]*domain.PaymentTransaction, error) {
	ret := _m.Called(ctx, tenantID, p)

	if len(ret) == 0 {
		panic("no return value specified for ListByTenant")
	}

	var r0 []*domain.PaymentTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, repository.ListParams) ([]*domain.PaymentTransaction, error)); ok {
		return rf(ctx, tenantID, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, repository.ListParams) []*domain.PaymentTransaction); ok {
		r0 = rf(ctx, tenantID, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.PaymentTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, repository.ListParams) error); ok {
		r1 = rf(ctx, tenantID, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionStore_ListByTenant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByTenant'
type MockTransactionStore_ListByTenant_Call struct {
	*mock.Call
}

// ListByTenant is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID int64
//   - p repository.ListParams
func (_e *MockTransactionStore_Expecter) ListByTenant(ctx interface{}, tenantID interface{}, p interface{}) *MockTransactionStore_ListByTenant_Call {
	return &MockTransactionStore_ListByTenant_Call{Call: _e.mock.On("ListByTenant", ctx, tenantID, p)}
}

func (_c *MockTransactionStore_ListByTenant_Call) Run(run func(ctx context.Context, tenantID int64, p repository.ListParams)) *MockTransactionStore_ListByTenant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(repository.ListParams))
	})
	return _c
}

func (_c *MockTransactionStore_ListByTenant_Call) Return(_a0 []*domain.PaymentTransaction, _a1 error) *MockTransactionStore_ListByTenant_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionStore_ListByTenant_Call) RunAndReturn(run func(context.Context, int64, repository.ListParams) ([]*domain.PaymentTransaction, error)) *MockTransactionStore_ListByTenant_Call {
	_c.Call.Return(run)
	return _c
}

// ListDistinctTenants provides a mock function with given fields: ctx
func (_m *MockTransactionStore) ListDistinctTenants(ctx context.Context) ([]int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListDistinctTenants")
	}

	var r0 []int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []int64); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionStore_ListDistinctTenants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDistinctTenants'
type MockTransactionStore_ListDistinctTenants_Call struct {
	*mock.Call
}

// ListDistinctTenants is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTransactionStore_Expecter) ListDistinctTenants(ctx interface{}) *MockTransactionStore_ListDistinctTenants_Call {
	return &MockTransactionStore_ListDistinctTenants_Call{Call: _e.mock.On("ListDistinctTenants", ctx)}
}

func (_c *MockTransactionStore_ListDistinctTenants_Call) Run(run func(ctx context.Context)) *MockTransactionStore_ListDistinctTenants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTransactionStore_ListDistinctTenants_Call) Return(_a0 []int64, _a1 error) *MockTransactionStore_ListDistinctTenants_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionStore_ListDistinctTenants_Call) RunAndReturn(run func(context.Context) ([]int64, error)) *MockTransactionStore_ListDistinctTenants_Call {
	_c.Call.Return(run)
	return _c
}

// ListExpired provides a mock function with given fields: ctx, limit
func (_m *MockTransactionStore) ListExpired(ctx context.Context, limit int) ([]*domain.PaymentTransaction, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListExpired")
	}

	var r0 []*domain.PaymentTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]*domain.PaymentTransaction, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []*domain.PaymentTransaction); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.PaymentTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionStore_ListExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListExpired'
type MockTransactionStore_ListExpired_Call struct {
	*mock.Call
}

// ListExpired is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *MockTransactionStore_Expecter) ListExpired(ctx interface{}, limit interface{}) *MockTransactionStore_ListExpired_Call {
	return &MockTransactionStore_ListExpired_Call{Call: _e.mock.On("ListExpired", ctx, limit)}
}

func (_c *MockTransactionStore_ListExpired_Call) Run(run func(ctx context.Context, limit int)) *MockTransactionStore_ListExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockTransactionStore_ListExpired_Call) Return(_a0 []*domain.PaymentTransaction, _a1 error) *MockTransactionStore_ListExpired_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionStore_ListExpired_Call) RunAndReturn(run func(context.Context, int) ([]*domain.PaymentTransaction, error)) *MockTransactionStore_ListExpired_Call {
	_c.Call.Return(run)
	return _c
}

// SumPendingSettlement provides a mock function with given fields: ctx, tenantID
func (_m *MockTransactionStore) SumPendingSettlement(ctx context.Context, tenantID int64) (*repository.PendingSettlementSums, error) {
	ret := _m.Called(ctx, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for SumPendingSettlement")
	}

	var r0 *repository.PendingSettlementSums
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*repository.PendingSettlementSums, error)); ok {
		return rf(ctx, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *repository.PendingSettlementSums); ok {
		r0 = rf(ctx, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.PendingSettlementSums)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionStore_SumPendingSettlement_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SumPendingSettlement'
type MockTransactionStore_SumPendingSettlement_Call struct {
	*mock.Call
}

// SumPendingSettlement is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID int64
func (_e *MockTransactionStore_Expecter) SumPendingSettlement(ctx interface{}, tenantID interface{}) *MockTransactionStore_SumPendingSettlement_Call {
	return &MockTransactionStore_SumPendingSettlement_Call{Call: _e.mock.On("SumPendingSettlement", ctx, tenantID)}
}

func (_c *MockTransactionStore_SumPendingSettlement_Call) Run(run func(ctx context.Context, tenantID int64)) *MockTransactionStore_SumPendingSettlement_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockTransactionStore_SumPendingSettlement_Call) Return(_a0 *repository.PendingSettlementSums, _a1 error) *MockTransactionStore_SumPendingSettlement_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionStore_SumPendingSettlement_Call) RunAndReturn(run func(context.Context, int64) (*repository.PendingSettlementSums, error)) *MockTransactionStore_SumPendingSettlement_Call {
	_c.Call.Return(run)
	return _c
}

// SumSettled provides a mock function with given fields: ctx, tenantID
func (_m *MockTransactionStore) SumSettled(ctx context.Context, tenantID int64) (*repository.PendingSettlementSums, error) {
	ret := _m.Called(ctx, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for SumSettled")
	}

	var r0 *repository.PendingSettlementSums
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*repository.PendingSettlementSums, error)); ok {
		return rf(ctx, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *repository.PendingSettlementSums); ok {
		r0 = rf(ctx, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.PendingSettlementSums)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionStore_SumSettled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SumSettled'
type MockTransactionStore_SumSettled_Call struct {
	*mock.Call
}

// SumSettled is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID int64
func (_e *MockTransactionStore_Expecter) SumSettled(ctx interface{}, tenantID interface{}) *MockTransactionStore_SumSettled_Call {
	return &MockTransactionStore_SumSettled_Call{Call: _e.mock.On("SumSettled", ctx, tenantID)}
}

func (_c *MockTransactionStore_SumSettled_Call) Run(run func(ctx context.Context, tenantID int64)) *MockTransactionStore_SumSettled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockTransactionStore_SumSettled_Call) Return(_a0 *repository.PendingSettlementSums, _a1 error) *MockTransactionStore_SumSettled_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionStore_SumSettled_Call) RunAndReturn(run func(context.Context, int64) (*repository.PendingSettlementSums, error)) *MockTransactionStore_SumSettled_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, txn
func (_m *MockTransactionStore) Update(ctx context.Context, txn *domain.PaymentTransaction) error {
	ret := _m.Called(ctx, txn)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.PaymentTransaction) error); ok {
		r0 = rf(ctx, txn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionStore_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTransactionStore_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - txn *domain.PaymentTransaction
func (_e *MockTransactionStore_Expecter) Update(ctx interface{}, txn interface{}) *MockTransactionStore_Update_Call {
	return &MockTransactionStore_Update_Call{Call: _e.mock.On("Update", ctx, txn)}
}

func (_c *MockTransactionStore_Update_Call) Run(run func(ctx context.Context, txn *domain.PaymentTransaction)) *MockTransactionStore_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.PaymentTransaction))
	})
	return _c
}

func (_c *MockTransactionStore_Update_Call) Return(_a0 error) *MockTransactionStore_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionStore_Update_Call) RunAndReturn(run func(context.Context, *domain.PaymentTransaction) error) *MockTransactionStore_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransactionStore creates a new instance of MockTransactionStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionStore {
	mock := &MockTransactionStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
