// Code generated by mockery v2.53.6. DO NOT EDIT.

package service

import (
	context "context"

	domain "github.com/dengankarya/connector/internal/payment/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockLedgerRecorder is an autogenerated mock type for the LedgerRecorder type
type MockLedgerRecorder struct {
	mock.Mock
}

type MockLedgerRecorder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLedgerRecorder) EXPECT() *MockLedgerRecorder_Expecter {
	return &MockLedgerRecorder_Expecter{mock: &_m.Mock}
}

// RecordManualPayment provides a mock function with given fields: ctx, txn
func (_m *MockLedgerRecorder) RecordManualPayment(ctx context.Context, txn *domain.PaymentTransaction) error {
	ret := _m.Called(ctx, txn)

	if len(ret) == 0 {
		panic("no return value specified for RecordManualPayment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.PaymentTransaction) error); ok {
		r0 = rf(ctx, txn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLedgerRecorder_RecordManualPayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordManualPayment'
type MockLedgerRecorder_RecordManualPayment_Call struct {
	*mock.Call
}

// RecordManualPayment is a helper method to define mock.On call
//   - ctx context.Context
//   - txn *domain.PaymentTransaction
func (_e *MockLedgerRecorder_Expecter) RecordManualPayment(ctx interface{}, txn interface{}) *MockLedgerRecorder_RecordManualPayment_Call {
	return &MockLedgerRecorder_RecordManualPayment_Call{Call: _e.mock.On("RecordManualPayment", ctx, txn)}
}

func (_c *MockLedgerRecorder_RecordManualPayment_Call) Run(run func(ctx context.Context, txn *domain.PaymentTransaction)) *MockLedgerRecorder_RecordManualPayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.PaymentTransaction))
	})
	return _c
}

func (_c *MockLedgerRecorder_RecordManualPayment_Call) Return(_a0 error) *MockLedgerRecorder_RecordManualPayment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLedgerRecorder_RecordManualPayment_Call) RunAndReturn(run func(context.Context, *domain.PaymentTransaction) error) *MockLedgerRecorder_RecordManualPayment_Call {
	_c.Call.Return(run)
	return _c
}

// RecordRefund provides a mock function with given fields: ctx, txn, eventID, refundAmount
func (_m *MockLedgerRecorder) RecordRefund(ctx context.Context, txn *domain.PaymentTransaction, eventID uuid.UUID, refundAmount int64) error {
	ret := _m.Called(ctx, txn, eventID, refundAmount)

	if len(ret) == 0 {
		panic("no return value specified for RecordRefund")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.PaymentTransaction, uuid.UUID, int64) error); ok {
		r0 = rf(ctx, txn, eventID, refundAmount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLedgerRecorder_RecordRefund_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordRefund'
type MockLedgerRecorder_RecordRefund_Call struct {
	*mock.Call
}

// RecordRefund is a helper method to define mock.On call
//   - ctx context.Context
//   - txn *domain.PaymentTransaction
//   - eventID uuid.UUID
//   - refundAmount int64
func (_e *MockLedgerRecorder_Expecter) RecordRefund(ctx interface{}, txn interface{}, eventID interface{}, refundAmount interface{}) *MockLedgerRecorder_RecordRefund_Call {
	return &MockLedgerRecorder_RecordRefund_Call{Call: _e.mock.On("RecordRefund", ctx, txn, eventID, refundAmount)}
}

func (_c *MockLedgerRecorder_RecordRefund_Call) Run(run func(ctx context.Context, txn *domain.PaymentTransaction, eventID uuid.UUID, refundAmount int64)) *MockLedgerRecorder_RecordRefund_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.PaymentTransaction), args[2].(uuid.UUID), args[3].(int64))
	})
	return _c
}

func (_c *MockLedgerRecorder_RecordRefund_Call) Return(_a0 error) *MockLedgerRecorder_RecordRefund_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLedgerRecorder_RecordRefund_Call) RunAndReturn(run func(context.Context, *domain.PaymentTransaction, uuid.UUID, int64) error) *MockLedgerRecorder_RecordRefund_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLedgerRecorder creates a new instance of MockLedgerRecorder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLedgerRecorder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLedgerRecorder {
	mock := &MockLedgerRecorder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
