// Code generated by mockery v2.53.6. DO NOT EDIT.

package service

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockTxRunnerIface is an autogenerated mock type for the TxRunnerIface type
type MockTxRunnerIface struct {
	mock.Mock
}

type MockTxRunnerIface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTxRunnerIface) EXPECT() *MockTxRunnerIface_Expecter {
	return &MockTxRunnerIface_Expecter{mock: &_m.Mock}
}

// RunInTx provides a mock function with given fields: ctx, fn
func (_m *MockTxRunnerIface) RunInTx(ctx context.Context, fn func(context.Context) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for RunInTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTxRunnerIface_RunInTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunInTx'
type MockTxRunnerIface_RunInTx_Call struct {
	*mock.Call
}

// RunInTx is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(context.Context) error
func (_e *MockTxRunnerIface_Expecter) RunInTx(ctx interface{}, fn interface{}) *MockTxRunnerIface_RunInTx_Call {
	return &MockTxRunnerIface_RunInTx_Call{Call: _e.mock.On("RunInTx", ctx, fn)}
}

func (_c *MockTxRunnerIface_RunInTx_Call) Run(run func(ctx context.Context, fn func(context.Context) error)) *MockTxRunnerIface_RunInTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(context.Context) error))
	})
	return _c
}

func (_c *MockTxRunnerIface_RunInTx_Call) Return(_a0 error) *MockTxRunnerIface_RunInTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTxRunnerIface_RunInTx_Call) RunAndReturn(run func(context.Context, func(context.Context) error) error) *MockTxRunnerIface_RunInTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTxRunnerIface creates a new instance of MockTxRunnerIface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTxRunnerIface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTxRunnerIface {
	mock := &MockTxRunnerIface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
