// Code generated by mockery v2.53.6. DO NOT EDIT.

package jobs

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	provider "github.com/dengankarya/connector/internal/payment/provider"
)

// MockRefundStatusChecker is an autogenerated mock type for the RefundStatusChecker type
type MockRefundStatusChecker struct {
	mock.Mock
}

type MockRefundStatusChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRefundStatusChecker) EXPECT() *MockRefundStatusChecker_Expecter {
	return &MockRefundStatusChecker_Expecter{mock: &_m.Mock}
}

// GetRefundsByPaymentID provides a mock function with given fields: ctx, paymentID
func (_m *MockRefundStatusChecker) GetRefundsByPaymentID(ctx context.Context, paymentID string) ([]provider.Refund, error) {
	ret := _m.Called(ctx, paymentID)

	if len(ret) == 0 {
		panic("no return value specified for GetRefundsByPaymentID")
	}

	var r0 []provider.Refund
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]provider.Refund, error)); ok {
		return rf(ctx, paymentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []provider.Refund); ok {
		r0 = rf(ctx, paymentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]provider.Refund)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, paymentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRefundStatusChecker_GetRefundsByPaymentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRefundsByPaymentID'
type MockRefundStatusChecker_GetRefundsByPaymentID_Call struct {
	*mock.Call
}

// GetRefundsByPaymentID is a helper method to define mock.On call
//   - ctx context.Context
//   - paymentID string
func (_e *MockRefundStatusChecker_Expecter) GetRefundsByPaymentID(ctx interface{}, paymentID interface{}) *MockRefundStatusChecker_GetRefundsByPaymentID_Call {
	return &MockRefundStatusChecker_GetRefundsByPaymentID_Call{Call: _e.mock.On("GetRefundsByPaymentID", ctx, paymentID)}
}

func (_c *MockRefundStatusChecker_GetRefundsByPaymentID_Call) Run(run func(ctx context.Context, paymentID string)) *MockRefundStatusChecker_GetRefundsByPaymentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRefundStatusChecker_GetRefundsByPaymentID_Call) Return(_a0 []provider.Refund, _a1 error) *MockRefundStatusChecker_GetRefundsByPaymentID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRefundStatusChecker_GetRefundsByPaymentID_Call) RunAndReturn(run func(context.Context, string) ([]provider.Refund, error)) *MockRefundStatusChecker_GetRefundsByPaymentID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRefundStatusChecker creates a new instance of MockRefundStatusChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRefundStatusChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRefundStatusChecker {
	mock := &MockRefundStatusChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
