// Code generated by mockery v2.53.6. DO NOT EDIT.

package provider

import (
	context "context"

	provider "github.com/dengankarya/connector/internal/payment/provider"
	mock "github.com/stretchr/testify/mock"
)

// MockPaymentProvider is an autogenerated mock type for the PaymentProvider type
type MockPaymentProvider struct {
	mock.Mock
}

type MockPaymentProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentProvider) EXPECT() *MockPaymentProvider_Expecter {
	return &MockPaymentProvider_Expecter{mock: &_m.Mock}
}

// CancelInvoice provides a mock function with given fields: ctx, invoiceID
func (_m *MockPaymentProvider) CancelInvoice(ctx context.Context, invoiceID string) error {
	ret := _m.Called(ctx, invoiceID)

	if len(ret) == 0 {
		panic("no return value specified for CancelInvoice")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, invoiceID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPaymentProvider_CancelInvoice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelInvoice'
type MockPaymentProvider_CancelInvoice_Call struct {
	*mock.Call
}

// CancelInvoice is a helper method to define mock.On call
//   - ctx context.Context
//   - invoiceID string
func (_e *MockPaymentProvider_Expecter) CancelInvoice(ctx interface{}, invoiceID interface{}) *MockPaymentProvider_CancelInvoice_Call {
	return &MockPaymentProvider_CancelInvoice_Call{Call: _e.mock.On("CancelInvoice", ctx, invoiceID)}
}

func (_c *MockPaymentProvider_CancelInvoice_Call) Run(run func(ctx context.Context, invoiceID string)) *MockPaymentProvider_CancelInvoice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPaymentProvider_CancelInvoice_Call) Return(_a0 error) *MockPaymentProvider_CancelInvoice_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPaymentProvider_CancelInvoice_Call) RunAndReturn(run func(context.Context, string) error) *MockPaymentProvider_CancelInvoice_Call {
	_c.Call.Return(run)
	return _c
}

// CreateInvoice provides a mock function with given fields: ctx, req
func (_m *MockPaymentProvider) CreateInvoice(ctx context.Context, req provider.CreateInvoiceRequest) (*provider.Invoice, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateInvoice")
	}

	var r0 *provider.Invoice
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, provider.CreateInvoiceRequest) (*provider.Invoice, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, provider.CreateInvoiceRequest) *provider.Invoice); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*provider.Invoice)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, provider.CreateInvoiceRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentProvider_CreateInvoice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInvoice'
type MockPaymentProvider_CreateInvoice_Call struct {
	*mock.Call
}

// CreateInvoice is a helper method to define mock.On call
//   - ctx context.Context
//   - req provider.CreateInvoiceRequest
func (_e *MockPaymentProvider_Expecter) CreateInvoice(ctx interface{}, req interface{}) *MockPaymentProvider_CreateInvoice_Call {
	return &MockPaymentProvider_CreateInvoice_Call{Call: _e.mock.On("CreateInvoice", ctx, req)}
}

func (_c *MockPaymentProvider_CreateInvoice_Call) Run(run func(ctx context.Context, req provider.CreateInvoiceRequest)) *MockPaymentProvider_CreateInvoice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(provider.CreateInvoiceRequest))
	})
	return _c
}

func (_c *MockPaymentProvider_CreateInvoice_Call) Return(_a0 *provider.Invoice, _a1 error) *MockPaymentProvider_CreateInvoice_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentProvider_CreateInvoice_Call) RunAndReturn(run func(context.Context, provider.CreateInvoiceRequest) (*provider.Invoice, error)) *MockPaymentProvider_CreateInvoice_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePayout provides a mock function with given fields: ctx, req
func (_m *MockPaymentProvider) CreatePayout(ctx context.Context, req provider.CreatePayoutRequest) (*provider.Payout, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreatePayout")
	}

	var r0 *provider.Payout
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, provider.CreatePayoutRequest) (*provider.Payout, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, provider.CreatePayoutRequest) *provider.Payout); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*provider.Payout)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, provider.CreatePayoutRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentProvider_CreatePayout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePayout'
type MockPaymentProvider_CreatePayout_Call struct {
	*mock.Call
}

// CreatePayout is a helper method to define mock.On call
//   - ctx context.Context
//   - req provider.CreatePayoutRequest
func (_e *MockPaymentProvider_Expecter) CreatePayout(ctx interface{}, req interface{}) *MockPaymentProvider_CreatePayout_Call {
	return &MockPaymentProvider_CreatePayout_Call{Call: _e.mock.On("CreatePayout", ctx, req)}
}

func (_c *MockPaymentProvider_CreatePayout_Call) Run(run func(ctx context.Context, req provider.CreatePayoutRequest)) *MockPaymentProvider_CreatePayout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(provider.CreatePayoutRequest))
	})
	return _c
}

func (_c *MockPaymentProvider_CreatePayout_Call) Return(_a0 *provider.Payout, _a1 error) *MockPaymentProvider_CreatePayout_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentProvider_CreatePayout_Call) RunAndReturn(run func(context.Context, provider.CreatePayoutRequest) (*provider.Payout, error)) *MockPaymentProvider_CreatePayout_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRefund provides a mock function with given fields: ctx, req
func (_m *MockPaymentProvider) CreateRefund(ctx context.Context, req provider.CreateRefundRequest) (*provider.Refund, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateRefund")
	}

	var r0 *provider.Refund
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, provider.CreateRefundRequest) (*provider.Refund, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, provider.CreateRefundRequest) *provider.Refund); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*provider.Refund)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, provider.CreateRefundRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentProvider_CreateRefund_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRefund'
type MockPaymentProvider_CreateRefund_Call struct {
	*mock.Call
}

// CreateRefund is a helper method to define mock.On call
//   - ctx context.Context
//   - req provider.CreateRefundRequest
func (_e *MockPaymentProvider_Expecter) CreateRefund(ctx interface{}, req interface{}) *MockPaymentProvider_CreateRefund_Call {
	return &MockPaymentProvider_CreateRefund_Call{Call: _e.mock.On("CreateRefund", ctx, req)}
}

func (_c *MockPaymentProvider_CreateRefund_Call) Run(run func(ctx context.Context, req provider.CreateRefundRequest)) *MockPaymentProvider_CreateRefund_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(provider.CreateRefundRequest))
	})
	return _c
}

func (_c *MockPaymentProvider_CreateRefund_Call) Return(_a0 *provider.Refund, _a1 error) *MockPaymentProvider_CreateRefund_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentProvider_CreateRefund_Call) RunAndReturn(run func(context.Context, provider.CreateRefundRequest) (*provider.Refund, error)) *MockPaymentProvider_CreateRefund_Call {
	_c.Call.Return(run)
	return _c
}

// GetInvoice provides a mock function with given fields: ctx, invoiceID
func (_m *MockPaymentProvider) GetInvoice(ctx context.Context, invoiceID string) (*provider.Invoice, error) {
	ret := _m.Called(ctx, invoiceID)

	if len(ret) == 0 {
		panic("no return value specified for GetInvoice")
	}

	var r0 *provider.Invoice
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*provider.Invoice, error)); ok {
		return rf(ctx, invoiceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *provider.Invoice); ok {
		r0 = rf(ctx, invoiceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*provider.Invoice)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, invoiceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentProvider_GetInvoice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInvoice'
type MockPaymentProvider_GetInvoice_Call struct {
	*mock.Call
}

// GetInvoice is a helper method to define mock.On call
//   - ctx context.Context
//   - invoiceID string
func (_e *MockPaymentProvider_Expecter) GetInvoice(ctx interface{}, invoiceID interface{}) *MockPaymentProvider_GetInvoice_Call {
	return &MockPaymentProvider_GetInvoice_Call{Call: _e.mock.On("GetInvoice", ctx, invoiceID)}
}

func (_c *MockPaymentProvider_GetInvoice_Call) Run(run func(ctx context.Context, invoiceID string)) *MockPaymentProvider_GetInvoice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPaymentProvider_GetInvoice_Call) Return(_a0 *provider.Invoice, _a1 error) *MockPaymentProvider_GetInvoice_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentProvider_GetInvoice_Call) RunAndReturn(run func(context.Context, string) (*provider.Invoice, error)) *MockPaymentProvider_GetInvoice_Call {
	_c.Call.Return(run)
	return _c
}

// ParseWebhookEvent provides a mock function with given fields: ctx, payload
func (_m *MockPaymentProvider) ParseWebhookEvent(ctx context.Context, payload []byte) (*provider.WebhookEvent, error) {
	ret := _m.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for ParseWebhookEvent")
	}

	var r0 *provider.WebhookEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte) (*provider.WebhookEvent, error)); ok {
		return rf(ctx, payload)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte) *provider.WebhookEvent); ok {
		r0 = rf(ctx, payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*provider.WebhookEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = rf(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentProvider_ParseWebhookEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseWebhookEvent'
type MockPaymentProvider_ParseWebhookEvent_Call struct {
	*mock.Call
}

// ParseWebhookEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - payload []byte
func (_e *MockPaymentProvider_Expecter) ParseWebhookEvent(ctx interface{}, payload interface{}) *MockPaymentProvider_ParseWebhookEvent_Call {
	return &MockPaymentProvider_ParseWebhookEvent_Call{Call: _e.mock.On("ParseWebhookEvent", ctx, payload)}
}

func (_c *MockPaymentProvider_ParseWebhookEvent_Call) Run(run func(ctx context.Context, payload []byte)) *MockPaymentProvider_ParseWebhookEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte))
	})
	return _c
}

func (_c *MockPaymentProvider_ParseWebhookEvent_Call) Return(_a0 *provider.WebhookEvent, _a1 error) *MockPaymentProvider_ParseWebhookEvent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentProvider_ParseWebhookEvent_Call) RunAndReturn(run func(context.Context, []byte) (*provider.WebhookEvent, error)) *MockPaymentProvider_ParseWebhookEvent_Call {
	_c.Call.Return(run)
	return _c
}

// ProviderName provides a mock function with no fields
func (_m *MockPaymentProvider) ProviderName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ProviderName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockPaymentProvider_ProviderName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProviderName'
type MockPaymentProvider_ProviderName_Call struct {
	*mock.Call
}

// ProviderName is a helper method to define mock.On call
func (_e *MockPaymentProvider_Expecter) ProviderName() *MockPaymentProvider_ProviderName_Call {
	return &MockPaymentProvider_ProviderName_Call{Call: _e.mock.On("ProviderName")}
}

func (_c *MockPaymentProvider_ProviderName_Call) Run(run func()) *MockPaymentProvider_ProviderName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPaymentProvider_ProviderName_Call) Return(_a0 string) *MockPaymentProvider_ProviderName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPaymentProvider_ProviderName_Call) RunAndReturn(run func() string) *MockPaymentProvider_ProviderName_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateWebhookSignature provides a mock function with given fields: ctx, payload, headers
func (_m *MockPaymentProvider) ValidateWebhookSignature(ctx context.Context, payload []byte, headers map[string]string) error {
	ret := _m.Called(ctx, payload, headers)

	if len(ret) == 0 {
		panic("no return value specified for ValidateWebhookSignature")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte, map[string]string) error); ok {
		r0 = rf(ctx, payload, headers)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPaymentProvider_ValidateWebhookSignature_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateWebhookSignature'
type MockPaymentProvider_ValidateWebhookSignature_Call struct {
	*mock.Call
}

// ValidateWebhookSignature is a helper method to define mock.On call
//   - ctx context.Context
//   - payload []byte
//   - headers map[string]string
func (_e *MockPaymentProvider_Expecter) ValidateWebhookSignature(ctx interface{}, payload interface{}, headers interface{}) *MockPaymentProvider_ValidateWebhookSignature_Call {
	return &MockPaymentProvider_ValidateWebhookSignature_Call{Call: _e.mock.On("ValidateWebhookSignature", ctx, payload, headers)}
}

func (_c *MockPaymentProvider_ValidateWebhookSignature_Call) Run(run func(ctx context.Context, payload []byte, headers map[string]string)) *MockPaymentProvider_ValidateWebhookSignature_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte), args[2].(map[string]string))
	})
	return _c
}

func (_c *MockPaymentProvider_ValidateWebhookSignature_Call) Return(_a0 error) *MockPaymentProvider_ValidateWebhookSignature_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPaymentProvider_ValidateWebhookSignature_Call) RunAndReturn(run func(context.Context, []byte, map[string]string) error) *MockPaymentProvider_ValidateWebhookSignature_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPaymentProvider creates a new instance of MockPaymentProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentProvider {
	mock := &MockPaymentProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
